# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ac_control/visino_fcuRequest.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class visino_fcuRequest(genpy.Message):
  _md5sum = "0fabbef3999e74196457a8185716d089"
  _type = "ac_control/visino_fcuRequest"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# 客户端请求时发送的两个数字
bool vision_flag  # 请求中包含一个布尔值，表示视觉标志位
bool fcu_flag  # 请求中包含一个布尔值，表示飞控标志位
"""
  __slots__ = ['vision_flag','fcu_flag']
  _slot_types = ['bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       vision_flag,fcu_flag

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(visino_fcuRequest, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.vision_flag is None:
        self.vision_flag = False
      if self.fcu_flag is None:
        self.fcu_flag = False
    else:
      self.vision_flag = False
      self.fcu_flag = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2B().pack(_x.vision_flag, _x.fcu_flag))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 2
      (_x.vision_flag, _x.fcu_flag,) = _get_struct_2B().unpack(str[start:end])
      self.vision_flag = bool(self.vision_flag)
      self.fcu_flag = bool(self.fcu_flag)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2B().pack(_x.vision_flag, _x.fcu_flag))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 2
      (_x.vision_flag, _x.fcu_flag,) = _get_struct_2B().unpack(str[start:end])
      self.vision_flag = bool(self.vision_flag)
      self.fcu_flag = bool(self.fcu_flag)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2B = None
def _get_struct_2B():
    global _struct_2B
    if _struct_2B is None:
        _struct_2B = struct.Struct("<2B")
    return _struct_2B
# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ac_control/visino_fcuResponse.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class visino_fcuResponse(genpy.Message):
  _md5sum = "870dc7ec1852923b2539416414dfa0c9"
  _type = "ac_control/visino_fcuResponse"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# 服务器响应发送的数据
bool success       # 响应中包含一个布尔值，表示操作是否成功
bool vision_flag  # 响应中包含一个布尔值，表示视觉标志位
bool fcu_flag  # 响应中包含一个布尔值，表示飞控标志位
"""
  __slots__ = ['success','vision_flag','fcu_flag']
  _slot_types = ['bool','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       success,vision_flag,fcu_flag

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(visino_fcuResponse, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.success is None:
        self.success = False
      if self.vision_flag is None:
        self.vision_flag = False
      if self.fcu_flag is None:
        self.fcu_flag = False
    else:
      self.success = False
      self.vision_flag = False
      self.fcu_flag = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3B().pack(_x.success, _x.vision_flag, _x.fcu_flag))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 3
      (_x.success, _x.vision_flag, _x.fcu_flag,) = _get_struct_3B().unpack(str[start:end])
      self.success = bool(self.success)
      self.vision_flag = bool(self.vision_flag)
      self.fcu_flag = bool(self.fcu_flag)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3B().pack(_x.success, _x.vision_flag, _x.fcu_flag))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 3
      (_x.success, _x.vision_flag, _x.fcu_flag,) = _get_struct_3B().unpack(str[start:end])
      self.success = bool(self.success)
      self.vision_flag = bool(self.vision_flag)
      self.fcu_flag = bool(self.fcu_flag)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3B = None
def _get_struct_3B():
    global _struct_3B
    if _struct_3B is None:
        _struct_3B = struct.Struct("<3B")
    return _struct_3B
class visino_fcu(object):
  _type          = 'ac_control/visino_fcu'
  _md5sum = '5e11117ad059078a9af4671921a90b5c'
  _request_class  = visino_fcuRequest
  _response_class = visino_fcuResponse
