// Generated by gencpp from file ac_control/visino_fcu.msg
// DO NOT EDIT!


#ifndef AC_CONTROL_MESSAGE_VISINO_FCU_H
#define AC_CONTROL_MESSAGE_VISINO_FCU_H

#include <ros/service_traits.h>


#include <ac_control/visino_fcuRequest.h>
#include <ac_control/visino_fcuResponse.h>


namespace ac_control
{

struct visino_fcu
{

typedef visino_fcuRequest Request;
typedef visino_fcuResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct visino_fcu
} // namespace ac_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ac_control::visino_fcu > {
  static const char* value()
  {
    return "5e11117ad059078a9af4671921a90b5c";
  }

  static const char* value(const ::ac_control::visino_fcu&) { return value(); }
};

template<>
struct DataType< ::ac_control::visino_fcu > {
  static const char* value()
  {
    return "ac_control/visino_fcu";
  }

  static const char* value(const ::ac_control::visino_fcu&) { return value(); }
};


// service_traits::MD5Sum< ::ac_control::visino_fcuRequest> should match
// service_traits::MD5Sum< ::ac_control::visino_fcu >
template<>
struct MD5Sum< ::ac_control::visino_fcuRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ac_control::visino_fcu >::value();
  }
  static const char* value(const ::ac_control::visino_fcuRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ac_control::visino_fcuRequest> should match
// service_traits::DataType< ::ac_control::visino_fcu >
template<>
struct DataType< ::ac_control::visino_fcuRequest>
{
  static const char* value()
  {
    return DataType< ::ac_control::visino_fcu >::value();
  }
  static const char* value(const ::ac_control::visino_fcuRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ac_control::visino_fcuResponse> should match
// service_traits::MD5Sum< ::ac_control::visino_fcu >
template<>
struct MD5Sum< ::ac_control::visino_fcuResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ac_control::visino_fcu >::value();
  }
  static const char* value(const ::ac_control::visino_fcuResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ac_control::visino_fcuResponse> should match
// service_traits::DataType< ::ac_control::visino_fcu >
template<>
struct DataType< ::ac_control::visino_fcuResponse>
{
  static const char* value()
  {
    return DataType< ::ac_control::visino_fcu >::value();
  }
  static const char* value(const ::ac_control::visino_fcuResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AC_CONTROL_MESSAGE_VISINO_FCU_H
